[package]
name = "genjson"
version = "0.1.0"
edition = "2021"
description = "Generate json on the command line"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Apfelfrosch/genjson"
readme = "README.md"